# Generated by Django 4.2.21 on 2025-07-01 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Helpful URL Identifier.', max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Nails', 'Nails'), ('Waxing/Threading', 'Waxing/Threading'), ('Lashes', 'Lashes'), ('MakeUp', 'Makeup')], help_text='Please select a Category.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='services.category'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
