# Generated by Django 4.2.21 on 2025-08-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_category_options_alter_treatment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
    ]
