# Generated by Django 4.2.23 on 2025-06-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='is_active',
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
