# Generated by Django 4.2.21 on 2025-07-05 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_remove_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('name', models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='availabilityblock',
            name='date',
        ),
        migrations.AddField(
            model_name='availabilityblock',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='availabilityblock',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='availabilityblock',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, help_text='Which days of the week this block applies to', to='bookings.weekday'),
        ),
    ]
