# Generated by Django 4.2.23 on 2025-06-14 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_availability_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
