# Generated by Django 4.2.21 on 2025-08-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_weekday_remove_availabilityblock_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
            preserve_default=False,
        ),
    ]
