# Generated by Django 4.2.21 on 2025-08-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_availability_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='availability',
            field=models.OneToOneField(blank=True, help_text='Which pre-generated slot this booking occupies.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='bookings.availability'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='pending', max_length=10),
        ),
    ]
